### ISSUE TITLE
Unhandled error on SimpleStringTest.php

### ISSUE THREAD

**Issue by ghost** [klaussilveira/SimpleString#6]
Unhandled error occured on SimpleStringTest.php file:

**Fatal error: Class 'PHPUnit_Framework_TestCase' not found in C:\WWW\index\klaussilveira-SimpleString-fe6517e\SimpleStringTest.php on line 17**

**Comment by klaussilveira** [comment]
Do you have PHPUnit installed?

**Comment by ghost** [comment]
Yes, but i say "Unhandled". :)
its better to handle PHPUnit_Framework class/file for avoiding error.

**Comment by klaussilveira** [comment]
No one will run unit tests along with the library in production, that's not the purpose. The dependency for running unit tests is quite clear, there's absolutely no need to handle this.
